const strings = {
  ar: {
    brand: 'استور أبو الدهب',
    brand_sub: 'مكان واحد لكل خدماتك',
    hero_title: 'خدمات تطوير مواقع احترافية',
    hero_desc: 'اختر الخطة المناسبة، وبعد الطلب نحدد معك الصفحات والألوان والنماذج بالتفصيل قبل البدء.',
    enter_market: 'ادخل السوق',
    free_title: 'خطط بدومين مجاني',
    plan_basic: 'عادي',
    plan_pro: 'مميز',
    plan_special: 'مخصص',
    plan_basic_title: 'موقع بسيط',
    plan_pro_title: 'موقع تعريفي متكامل',
    plan_special_title: 'موقع شركة أو خدمات',
    brief_free: 'بدون دومين',
    deliver_2d: 'التسليم: ٢ أيام',
    deliver_4d: 'التسليم: ٤ أيام',
    deliver_7d: 'التسليم: ٧ أيام',
    feat_pages3: 'من 3 صفحات',
    feat_pages6: 'حتى 6 صفحات',
    feat_pages8: 'حتى 8 صفحات',
    feat_responsive: 'تصميم متجاوب',
    feat_whatsapp: 'واتساب مباشر',
    feat_services_section: 'قسم خدمات/أعمال',
    feat_form_advanced: 'نموذج تواصل متقدم',
    feat_all_from_pro: 'كل ميزات خطة مميز',
    feat_free_domain: 'دومين مجاني',
    order_service: 'طلب الخطة',
    footer_note: 'جميع الحقوق محفوظة - استور أبو الدهب ©'
  },
  en: {
    brand: 'Abd El Dahab Store',
    brand_sub
